export const TOP_PULL_TRIGGER_DISTANCE = 2;
export const TOP_PULL_RELEASE_DISTANCE = 20;
export const BOTTOM_TRIGGER_DISTANCE = 20;
export const BOTTOM_RELEASE_DISTANCE = 52;
export const EDGE_PULL_TRIGGER_DISTANCE = 42;
export const EDGE_END_DRAG_VELOCITY_MIN = 0.55;
